TransactionsFetcher:
  cron: '*/30 * * * * *'
  class: TransactionsFetcher

DailyStatWorker:
  cron: '0 4 * * *'
  class: DailyStatWorker

DivergenceNotifierWorker:
  cron: '*/15 * * * *'
  class: DivergenceNotifierWorker

